jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3.5.2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build
      run: ./gradlew build --no-daemon
name: Build PRs
on:
  repository_dispatch:
    types: trigger-ga___buildprs.yml
