jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: Vankka/pr-target-branch-action@v1.1
      with:
        change-to: develop
        comment: 'Your PR was set to `master` but as our [Contributing Guidelines](https://github.com/DiscordSRV/DiscordSRV/blob/master/CONTRIBUTING.md)
          state, PRs should be sent to `develop`

          The base branch of this PR has been automatically changed to `develop`,
          please check that there are no merge conflicts.

          '
        exclude: develop
        target: master
name: Check that PRs are set to develop
on:
  repository_dispatch:
    types: trigger-ga___prbranch.yml
