jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3.5.2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Set version to release
      run: ./gradlew --no-daemon unSnapshotVersion
    - continue-on-error: true
      name: Commit release version
      run: ./gradlew --no-daemon commitVersion
    - continue-on-error: true
      env:
        REPO_PASSWORD: ${{ secrets.NEXUS_CI }}
      name: Build & deploy to Nexus
      run: ./gradlew --no-daemon publish
    - continue-on-error: true
      name: Push to master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
name: Build & deploy release
on:
  repository_dispatch:
    types: trigger-ga___releases.yml
