jobs:
  action:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dessant/support-requests@v3.0.0
      with:
        close-issue: true
        issue-comment: 'We use the issue tracker exclusively for bug reports and feature
          requests. However, this issue appears to be a support request. Please join
          our Discord at https://discordsrv.com/discord and go to the #create-a-ticket
          channel for help with installing or configuring DiscordSRV.

          '
        issue-lock-reason: off-topic
        lock-issue: false
        support-label: support
name: Support Requests
on:
  repository_dispatch:
    types: trigger-ga___support.yml
permissions:
  issues: write
